#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
ROLLBAR_TOKEN=$(dokku config:get "$APP" ROLLBAR_TOKEN || echo)

if [[ $ROLLBAR_TOKEN ]]; then
  echo "-----> Notifying Rollbar ..."

  ENVIRONMENT=$(
    dokku config:get "$APP" ROLLBAR_ENV ||
    dokku config:get "$APP" RAILS_ENV ||
    dokku config:get "$APP" RACK_ENV ||
    echo 'production'
  )
  REVISION=$(cd $DOKKU_ROOT/$APP && git log -n 1 --pretty=format:"%H" 2>/dev/null)
  LOCAL_USERNAME=`whoami`

  ROLLBAR_RESULT=$(curl -s https://api.rollbar.com/api/1/deploy/ \
    -F access_token=$ROLLBAR_TOKEN \
    -F environment=$ENVIRONMENT \
    -F revision=$REVISION \
    -F local_username=$LOCAL_USERNAME
  )

  echo "       ${ROLLBAR_RESULT}"
fi
